sequenceDiagram
    participant Parser as Parser (Bison)
    participant CH as ContextHandler
    participant PC as ParsingContext
    participant NM as NameMangler
    participant Builder as LexemeInfoBuilder
    participant ST as SymbolTable

    Parser->>PC: new ParsingContext(symbolTable)
    PC->>NM: new NameMangler() x3
    PC->>Builder: new LexemeInfoBuilder()
    Parser->>CH: add(ctx)

    loop Grammar reductions
        Parser->>CH: current()
        Parser->>Builder: metadataBuilder() attributes
        Parser->>PC: declaredIdentifiers().add(identifier)
    end

    Parser->>CH: publish()
    CH->>Builder: build() LexemeInfo
    loop For each declared identifier
        CH->>NM: outerScopes().getNameMangled(identifier)
        CH->>ST: put(completeIdentifier, LexemeInfo)
    end

    Parser->>CH: pop()