// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/lexer/Lexer.flex

package lexer;

import lexer.semantics.*;
import lexer.semantics.SemanticAnalyzer.Result;
import parser.Parser;
import utils.enums.ElementaryType;
import utils.SymbolTable;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements Parser.Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\0"+
    "\1\4\1\5\1\6\2\0\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\0\1\17\1\20\1\21"+
    "\3\22\1\23\1\22\1\24\1\25\1\26\1\27\1\0"+
    "\1\30\3\0\3\31\1\32\2\31\1\33\1\34\3\33"+
    "\1\35\1\36\1\35\1\33\1\35\1\33\1\35\1\37"+
    "\1\35\6\33\1\40\1\0\1\41\1\0\1\42\1\0"+
    "\3\31\1\32\2\31\1\33\1\34\3\33\1\35\1\36"+
    "\1\35\1\33\1\35\1\33\1\35\1\37\1\35\6\33"+
    "\12\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\1\1\10\1\1\1\11\4\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\1\1\0\1\21\3\0\1\22"+
    "\1\0\2\23\1\24\3\0\4\25\1\0\1\12\2\0"+
    "\1\26\10\0\1\27\6\0\1\25\3\0\1\12\1\0"+
    "\1\30\1\31\1\0\1\2\1\27\1\0\1\25\3\0"+
    "\1\25\3\0\1\32\1\0\1\33\1\34\7\0\1\34"+
    "\3\0\1\35\1\0\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\43\0\106\0\43\0\151\0\214\0\43"+
    "\0\257\0\43\0\322\0\365\0\u0118\0\u013b\0\u015e\0\u0181"+
    "\0\u01a4\0\43\0\43\0\u01c7\0\43\0\43\0\u01ea\0\106"+
    "\0\43\0\u020d\0\151\0\u0230\0\43\0\u0253\0\u0276\0\u0299"+
    "\0\43\0\u02bc\0\u02df\0\u0302\0\u0325\0\u0348\0\u036b\0\u038e"+
    "\0\u03b1\0\u03d4\0\u03f7\0\u041a\0\43\0\u01ea\0\u043d\0\u0460"+
    "\0\u0483\0\257\0\u04a6\0\322\0\u04c9\0\u04ec\0\u050f\0\u0532"+
    "\0\u0555\0\u0578\0\u059b\0\u05be\0\43\0\u05e1\0\u0604\0\u0627"+
    "\0\u064a\0\u066d\0\u03f7\0\u041a\0\u0690\0\u0253\0\u06b3\0\u06d6"+
    "\0\u06f9\0\u071c\0\u073f\0\u0762\0\u0785\0\u07a8\0\u07cb\0\u06f9"+
    "\0\u066d\0\u07ee\0\u0811\0\u0834\0\u0857\0\u087a\0\u089d\0\u08c0"+
    "\0\u08e3\0\u0906\0\u0929\0\u0906\0\u094c\0\u096f\0\u0992\0\u09b5"+
    "\0\u09d8\0\u09d8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\2\1\6\1\7"+
    "\1\10\1\2\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\2\15\1\20\1\15\1\21\1\22\1\23\7\24"+
    "\1\25\1\26\1\27\43\0\4\30\1\31\1\30\1\32"+
    "\34\30\6\33\1\34\1\35\33\33\12\0\1\36\47\0"+
    "\7\37\34\0\7\40\33\0\1\41\41\0\1\42\1\43"+
    "\7\15\1\44\3\0\1\45\1\0\1\46\1\0\1\47"+
    "\1\50\2\0\1\51\15\0\1\42\1\43\4\15\1\52"+
    "\2\15\1\44\3\0\1\45\1\0\1\46\1\0\1\47"+
    "\1\50\2\0\1\51\5\0\1\53\7\0\1\42\1\43"+
    "\7\15\1\44\3\0\1\45\1\0\1\46\1\0\1\47"+
    "\1\50\2\0\1\51\5\0\1\54\7\0\1\42\1\43"+
    "\7\15\1\44\3\0\1\45\1\0\1\46\1\0\1\47"+
    "\1\50\2\0\1\51\30\0\1\55\31\0\7\24\3\0"+
    "\7\24\2\0\1\56\17\0\7\24\3\0\7\24\7\0"+
    "\1\30\1\0\1\30\10\0\7\57\3\0\2\57\2\0"+
    "\1\30\13\0\2\33\7\0\7\60\3\0\2\60\2\0"+
    "\1\33\5\0\2\36\2\0\6\36\1\61\30\36\17\0"+
    "\7\37\14\0\1\62\16\0\1\63\7\40\14\0\1\64"+
    "\17\0\7\65\34\0\7\66\34\0\7\67\34\0\7\70"+
    "\14\0\1\71\17\0\7\72\14\0\1\73\17\0\7\74"+
    "\11\0\1\75\2\0\1\76\17\0\7\77\14\0\1\100"+
    "\17\0\7\101\22\0\1\102\7\0\1\42\1\43\7\15"+
    "\1\44\3\0\1\45\1\0\1\46\1\0\1\47\1\50"+
    "\2\0\1\51\17\0\2\103\41\0\5\104\36\0\7\105"+
    "\3\0\2\105\27\0\7\33\3\0\2\33\10\0\2\36"+
    "\2\0\5\36\1\106\1\61\30\36\17\0\7\107\32\0"+
    "\1\110\1\0\7\65\34\0\7\66\4\0\1\75\1\0"+
    "\1\75\1\0\1\111\1\75\2\0\1\63\17\0\7\67"+
    "\1\112\32\0\1\113\7\70\6\0\1\46\25\0\7\70"+
    "\33\0\1\114\7\72\10\0\1\115\23\0\7\72\33\0"+
    "\1\116\7\74\11\0\1\50\22\0\7\74\33\0\1\117"+
    "\7\77\10\0\1\120\23\0\7\77\33\0\1\63\7\101"+
    "\14\0\1\51\17\0\7\121\3\0\2\121\27\0\7\122"+
    "\3\0\2\122\27\0\7\107\14\0\1\63\17\0\7\123"+
    "\54\0\1\75\22\0\7\124\34\0\7\125\34\0\7\126"+
    "\34\0\7\74\14\0\1\76\17\0\7\127\34\0\7\130"+
    "\34\0\7\30\3\0\2\30\25\0\1\131\1\0\7\123"+
    "\33\0\1\132\7\124\34\0\7\125\6\0\1\75\25\0"+
    "\7\126\10\0\1\75\23\0\7\127\11\0\1\75\22\0"+
    "\7\130\10\0\1\120\23\0\7\133\34\0\7\134\34\0"+
    "\7\133\1\135\33\0\7\136\34\0\7\136\1\137\33\0"+
    "\7\140\33\0\1\141\7\140\34\0\7\142\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2555];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\2\1\1\11\1\1\1\11"+
    "\7\1\2\11\1\1\2\11\1\1\1\0\1\11\3\0"+
    "\1\11\1\0\2\1\1\11\3\0\4\1\1\0\1\1"+
    "\2\0\1\11\10\0\1\1\6\0\1\11\3\0\1\1"+
    "\1\0\2\1\1\0\2\1\1\0\1\1\3\0\1\1"+
    "\3\0\1\1\1\0\2\1\7\0\1\1\3\0\1\1"+
    "\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Object yylval;
    private SemanticAnalyzer identifiers;
    private SemanticAnalyzer generic;

    public Object getLVal() {
        return this.yylval;
    }

    public void yyerror(String msg) {
        System.err.println("Line " + (yyline + 1) + ": " + msg);
    }

    public int saveYylval(String text, ElementaryType type, SemanticAnalyzer analyzer) {
        Result result = analyzer.analyze(yytext(), type);
        this.yylval = result.value;
        return result.tokenNumber;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in, SymbolTable symbolTable) {
      this.identifiers = new Identifiers(symbolTable);
    this.generic     = new Default(symbolTable);
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     return Parser.Lexer.YYEOF;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { yyerror("Invalid Character: " + yytext());
            }
            // fall through
          case 30: break;
          case 2:
            { 
            }
            // fall through
          case 31: break;
          case 3:
            { return '\"';
            }
            // fall through
          case 32: break;
          case 4:
            { return '#';
            }
            // fall through
          case 33: break;
          case 5:
            { return '\'';
            }
            // fall through
          case 34: break;
          case 6:
            { return '(';
            }
            // fall through
          case 35: break;
          case 7:
            { return ')';
            }
            // fall through
          case 36: break;
          case 8:
            { return ',';
            }
            // fall through
          case 37: break;
          case 9:
            { return '.';
            }
            // fall through
          case 38: break;
          case 10:
            { return saveYylval(yytext(), ElementaryType.UINT         , this.generic);
            }
            // fall through
          case 39: break;
          case 11:
            { return ':';
            }
            // fall through
          case 40: break;
          case 12:
            { return ';';
            }
            // fall through
          case 41: break;
          case 13:
            { return '=';
            }
            // fall through
          case 42: break;
          case 14:
            { return saveYylval(yytext(), ElementaryType.UNKNOWN      , this.identifiers);
            }
            // fall through
          case 43: break;
          case 15:
            { return '[';
            }
            // fall through
          case 44: break;
          case 16:
            { return ']';
            }
            // fall through
          case 45: break;
          case 17:
            { return saveYylval(yytext(), ElementaryType.WSTRING      , this.generic);
            }
            // fall through
          case 46: break;
          case 18:
            { return saveYylval(yytext(), ElementaryType.STRING       , this.generic);
            }
            // fall through
          case 47: break;
          case 19:
            { return saveYylval(yytext(), ElementaryType.SINT         , this.generic);
            }
            // fall through
          case 48: break;
          case 20:
            { return Parser.Lexer.RANGE_OP;
            }
            // fall through
          case 49: break;
          case 21:
            { return saveYylval(yytext(), ElementaryType.TIME         , this.generic);
            }
            // fall through
          case 50: break;
          case 22:
            { return Parser.Lexer.ASSIGN_OP;
            }
            // fall through
          case 51: break;
          case 23:
            { return saveYylval(yytext(), ElementaryType.REAL         , this.generic);
            }
            // fall through
          case 52: break;
          case 24:
            { return saveYylval(yytext(), ElementaryType.BYTE         , this.generic);
            }
            // fall through
          case 53: break;
          case 25:
            { return saveYylval(yytext(), ElementaryType.WORD         , this.generic);
            }
            // fall through
          case 54: break;
          case 26:
            { return saveYylval(yytext(), ElementaryType.DWORD        , this.generic);
            }
            // fall through
          case 55: break;
          case 27:
            { return saveYylval(yytext(), ElementaryType.DATE         , this.generic);
            }
            // fall through
          case 56: break;
          case 28:
            { return saveYylval(yytext(), ElementaryType.TIME_OF_DAY  , this.generic);
            }
            // fall through
          case 57: break;
          case 29:
            { return saveYylval(yytext(), ElementaryType.DATE_AND_TIME, this.generic);
            }
            // fall through
          case 58: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
